# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcard_source_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='cropped_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcard_crops/'),
        ),
    ]

